### ISSUE TITLE
crash when typing "tang ping"

### ISSUE THREAD

**Issue by foughter77** [shi-yan/broca#2]
🔥 Success!
💬 Response: I'm sorry, but "tang ping" is not an English word or phrase. Could you please provide me with a valid query?
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src/openai.rs:165:110
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /opt/local/libexec/rust/src/rustc-1.68.2-src/library/core/src/result.rs:1112:23
   4: broca::openai::search::{{closure}}
             at ./src/openai.rs:165:53
   5: broca::state::State::search::{{closure}}
             at ./src/state.rs:94:99
   6: broca::search::{{closure}}
             at ./src/main.rs:81:51
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
   8: tokio::runtime::coop::with_budget
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  11: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:304:45
  14: broca::search
             at ./src/main.rs:80:12
  15: broca::main::{{closure}}
             at ./src/main.rs:125:25
  16: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /opt/local/libexec/rust/src/rustc-1.68.2-src/library/alloc/src/boxed.rs:2002:9
  17: tauri::manager::WindowManager<R>::run_invoke_handler
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/manager.rs:1084:5
  18: tauri::window::Window<R>::on_message
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/window.rs:1287:11
  19: tauri::manager::WindowManager<R>::prepare_ipc_handler::{{closure}}
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/manager.rs:782:19
  20: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /opt/local/libexec/rust/src/rustc-1.68.2-src/library/alloc/src/boxed.rs:2002:9
  21: tauri_runtime_wry::create_ipc_handler::{{closure}}
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.12.2/src/lib.rs:3124:5
  22: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /opt/local/libexec/rust/src/rustc-1.68.2-src/library/alloc/src/boxed.rs:2002:9
  23: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /opt/local/libexec/rust/src/rustc-1.68.2-src/library/alloc/src/boxed.rs:2002:9
  24: wry::webview::wkwebview::InnerWebView::new::did_receive
             at /Users/lili/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.23.4/src/webview/wkwebview/mod.rs:102:11
  25: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

**Comment by shi-yan** [comment]
I added error handling for this case. this should be resolved now.
